all: main.cpp
	g++ -std=c++11 HOHdistro.cpp degree_distro.cpp gephifile.cpp nrt.cpp read_data.cpp OHdistro.cpp degree_z.cpp helper.cpp orientation.cpp sdf.cpp OOdistro.cpp density.cpp main.cpp output_edgelist.cpp vel_check.cpp analysis.cpp edgelist.cpp msd.cpp read_config.cpp -lyaml-cpp -o main	

clean:
	rm main
